services:
  front-end:
    image: benbsteven2002/file_explorer_x-front-end
    ports:
    
  back-end:
    image: benbsteven2002/file_explorer_x-back-end
    ports:
      - 3000:3000
    volumes:
      - /:/host
